# Generated by Django 3.2.25 on 2025-01-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=120)),
            ],
        ),
    ]
